# Default initial positions for gen3's ros2_control fake system

initial_positions:
  joint_1: 0
  joint_2: 0.261
  joint_3: -2.27
  joint_4: 0
  joint_5: 0.96
  joint_6: 1.5708
  robotiq_85_left_knuckle_joint: 0
